import Menu from '@/components/base/Menu'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Titillium_Web } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const titiliumRegular = Titillium_Web({ subsets: ['latin'], weight: "400", variable: "--font-regular" })
const titiliumBold = Titillium_Web({ subsets: ['latin'], weight: "700", variable: "--font-bold" })

export const metadata: Metadata = {
  title: 'Yu-Gi-Oh! App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <link rel="icon" href="../assets/favicon.ico" />
        <body
        className={`${inter.className} ${titiliumRegular.variable} ${titiliumBold.variable} font-regular text-white text-lg leading-relaxed bg-[#111111]`}
      >
        <main className="grid md:grid-cols-[300px,calc(100vw-300px)] h-screen">
          <Menu />
          <div className="flex h-full max-h-screen w-full flex-col bg-cover px-6 overflow-y-auto overflow-x-hidden">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
