import Menu from '@/components/base/Menu'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yu-Gi-Oh! App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body
        className={`${inter.className} text-gray-100 bg-[#09090B]`}
      >
        <main className="grid md:grid-cols-[300px,calc(80vw-300px)] h-screen ">
          <Menu />
          <div className="flex h-full max-h-screen w-full flex-col bg-cover">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
